services:
  - type: web
    name: sistema-os
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        sync: false   # você cola a URL do Neon aqui no painel do Render
      - key: SECRET_KEY
        generateValue: true
